name: unit_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.3'
          cache: true
          cache-dependency-path: go.sum

      - name: OS Version
        run: cat /etc/os-release

      - name: Go Version
        run: go version

      - name: Go Test
        run: |
          go test ./...
